<a href="https://colab.research.google.com/github/MattKim98/aipython/blob/main/20260605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('Iris.csv')
display(df_iris.head())

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

In [ ]:
print('iris 키: ',iris.keys())

iris 키:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('데이터:\n ',iris['data'][:5])

데이터:
  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print('특성 이름:',iris['feature_names'])

특성 이름: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print('타깃:\n ',iris['target'][:5])

타깃:
  [0 0 0 0 0]


In [ ]:
print('타깃 이름', iris['target_names'])

타깃 이름 ['setosa' 'versicolor' 'virginica']


In [ ]:
print('데이터 크기', iris['data'].shape)
print('타깃 크기', iris['target'].shape)

데이터 크기 (150, 4)
타깃 크기 (150,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'],\
                                                    random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
import numpy as np

X_new = np.array([[6, 3.5, 5, 1.5]])

In [ ]:
pred = knn.predict(X_new)
print(pred)

[1]


In [ ]:
print(iris['target_names'] [pred])

['versicolor']


In [ ]:
y_pred = knn.predict(X_test)
print('테스트 세트 예측 값:\n', y_pred)
print('테스트 세트 실제 타깃:\n', y_test)

테스트 세트 예측 값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트 세트 실제 타깃:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [ ]:
print(f'훈련 세트 정확도: {knn.score(X_train, y_train):.3f}')
print(f'테스트 세트 정확도: {knn.score(X_test, y_test):.3f}')

훈련 세트 정확도: 0.964
테스트 세트 정확도: 0.974


In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

#데이터 수집하기
wine = datasets.load_wine()
print('wine 키:', wine.keys())
print('데이터:\n', wine['data'][:5])
print('특성 이름:', wine['feature_names'])
print('타깃:\n', wine['target'][:5])
print('타깃 이름:', wine['target_names'])
print('데이터 크기:', wine['data'].shape)
print('타깃 크기:', wine['target'].shape)

#데이터 전처리하기
X_train, X_test, y_train, y_test = train_test_split(wine['data'], wine['target'],\
                                                    random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

#모델 생성하기
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

#모델 이용해 예측하기
y_pred knn.predict(X_test)
print('테스트 세트 예측 값:\n', y_pred)
print('테스트 세트 실제 타깃:\n', y_test)

#모델 평가하기
print(f'훈련 세트 정확도: {knn.score(X_train, y_train):.3f}')
print(f'테스트 세트 정확도: {knn.score(X_test, y_test):.3f}')